# Bun configuration file
# This file configures Bun's behavior for the project

[test]
# Test configuration
root = "./test"
preload = ["./test/setup.ts"]
coverageReporter  = ["text", "lcov"]
coverageDir = "test/coverage"
# Multiple patterns
coveragePathIgnorePatterns = [
  "test/**/*.ts",
  "*.config.js"
]

[test.reporter]
junit = "test/coverage/junit.xml"  # Output path for JUnit XML report

[run]
# Runtime configuration
bun = true
