x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 3

x-resources: &resources
  resources:
    limits:
      cpus: '0.5'
      memory: 256M

services:
  app:
    image: ghcr.io/feryardiant/learn-bun-elysia:${STAGING_BRANCH:-latest}
    container_name: elysia-app
    ports:
      - ${FORWARD_APP_PORT:-3000}:3000
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
      jaeger:
        condition: service_started
    env_file:
      - path: ../.env
        required: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      APP_URL: ${APP_URL:-http://localhost:${FORWARD_APP_PORT:-3000}}
      APP_DOMAIN: ${APP_DOMAIN:-localhost}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      BASE_PATH: ${BASE_PATH:-}
      AUTH_SECRET: ${AUTH_SECRET:-}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-secret}
      DB_NAME: ${DB_NAME:-elysia_app}

      # Email
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: 1025
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      SMTP_EMAIL: ${SMTP_EMAIL:-noreply@${APP_DOMAIN:-example.com}}

      # OTEL
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318}
    healthcheck:
      test: ["CMD-SHELL", "server health"]
      <<: *healthcheck
    deploy: *resources

  postgres:
    image: postgres:${DB_VERSION:-17.7}-${BASE_OS:-alpine}${BASE_VERSION:-3.23}
    container_name: elysia-db
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_NAME:-elysia_app}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/10-init-db.sql
      - ./local/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-elysia_app}"]
      <<: *healthcheck
    deploy: *resources

  mailpit:
    image: axllent/mailpit:v1.29
    container_name: elysia-mail
    ports:
      - ${FORWARD_MAIL_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_PORT:-8025}:8025
    environment:
      MP_DATABASE: /data/mailpit.db
    volumes:
      - ./local/mailpit:/data

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.15.0
    container_name: elysia-otel
    command: ["--config=/etc/jaeger/config.yml"]
    ports:
      - "${FORWARD_OTLP_GRPC_PORT:-4317}:4317" # OTLP gRPC
      - "${FORWARD_OTLP_HTTP_PORT:-4318}:4318" # OTLP HTTP
      - "${FORWARD_JAEGER_PORT:-16686}:16686"  # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - ./jaeger-ui-config.json:/etc/jaeger/config-ui.json
      - ./jaeger-config.yml:/etc/jaeger/config.yml
      - ./local/jaeger:/tmp
    deploy: *resources
